/*
 * Shared sticker file operations, used by both the bulk seeder
 * (scripts/fetch-stickers.mjs) and the dev picker UI (/dev/stickers).
 *
 * One implementation on purpose: the manifest and the service worker precache
 * list must never drift from what is actually on disk.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

export const STICKER_DIR = "public/stickers";
export const MANIFEST = "shared/data/stickers.json";
export const SW = "public/sw.js";
export const MAX_BYTES = 200_000;

export const CATEGORIES = [
  "celebrity",
  "movie",
  "place",
  "animal",
  "object",
  "number",
];

/** Starting points for the picker's search box, not a fixed shopping list. */
export const SUGGESTED_QUERIES = {
  celebrity: ["sunglasses cool", "celebrity wave", "superstar", "bollywood"],
  movie: ["movie clapper", "popcorn cinema", "film reel", "director action"],
  place: ["travel globe", "world landmark", "suitcase travel", "map pin"],
  animal: ["funny animal dance", "cute animal", "dancing cat", "elephant"],
  object: ["household objects", "random object", "lightbulb idea", "chai cup"],
  number: ["dice roll", "lucky number", "counting numbers", "bingo"],
};

export function listOnDisk(category) {
  const dir = join(STICKER_DIR, category);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".gif"))
    .sort();
}

export function readManifest() {
  if (!existsSync(MANIFEST)) return {};
  try {
    return JSON.parse(readFileSync(MANIFEST, "utf8"));
  } catch {
    return {};
  }
}

/**
 * Rebuilt from disk, so curating is just adding or deleting files. Metadata
 * from the previous manifest is carried over by src — without that, a
 * rebuild-only run silently wiped every title and source link.
 */
export function rebuildManifest() {
  const previous = readManifest();
  const known = new Map();
  for (const list of Object.values(previous)) {
    for (const entry of list ?? []) known.set(entry.src, entry);
  }

  const manifest = {};
  let bytes = 0;
  for (const category of CATEGORIES) {
    manifest[category] = listOnDisk(category).map((file) => {
      const src = `/stickers/${category}/${file}`;
      bytes += statSync(join(STICKER_DIR, category, file)).size;
      return known.get(src) ?? { src };
    });
  }
  writeFileSync(MANIFEST, JSON.stringify(manifest, null, 1) + "\n");
  syncServiceWorker(manifest);
  return { manifest, bytes };
}

/** Keep the precache list in step, or stickers stop working offline. */
export function syncServiceWorker(manifest = readManifest()) {
  if (!existsSync(SW)) return;
  const sw = readFileSync(SW, "utf8");
  const block = Object.values(manifest)
    .flat()
    .map((s) => s.src)
    .sort()
    .map((p) => `  "${p}"`)
    .join(",\n");
  const next = sw.replace(
    /(\/\/ Generated by scripts\/fetch-stickers\.mjs[^\n]*\n)[\s\S]*?(\n\];)/,
    `$1${block}$2`,
  );
  if (next !== sw) writeFileSync(SW, next);
}

export function setMetadata(category, file, meta) {
  const manifest = readManifest();
  const src = `/stickers/${category}/${file}`;
  manifest[category] = (manifest[category] ?? []).map((entry) =>
    entry.src === src ? { ...entry, ...meta } : entry,
  );
  writeFileSync(MANIFEST, JSON.stringify(manifest, null, 1) + "\n");
}

/** Returns { ok, reason?, bytes? }. Never throws on a bad candidate. */
export async function saveSticker({ category, id, downloadUrl, title, sourceUrl }) {
  if (!CATEGORIES.includes(category)) return { ok: false, reason: "bad category" };
  const dir = join(STICKER_DIR, category);
  mkdirSync(dir, { recursive: true });
  const file = `${id}.gif`;
  const path = join(dir, file);

  const res = await fetch(downloadUrl);
  if (!res.ok) return { ok: false, reason: `download ${res.status}` };
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.byteLength > MAX_BYTES) {
    return { ok: false, reason: `too big (${Math.round(buf.byteLength / 1024)}KB)` };
  }
  writeFileSync(path, buf);
  rebuildManifest();
  setMetadata(category, file, { title: title || "GIPHY sticker", url: sourceUrl });
  syncServiceWorker();
  return { ok: true, bytes: buf.byteLength };
}

export function removeSticker(category, file) {
  const path = join(STICKER_DIR, category, file.replace(/[^\w.-]/g, ""));
  if (!existsSync(path)) return { ok: false, reason: "not found" };
  rmSync(path);
  rebuildManifest();
  return { ok: true };
}

export async function searchStickers({ query, limit = 24, offset = 0, key }) {
  const url = new URL("https://api.giphy.com/v1/stickers/search");
  url.searchParams.set("api_key", key);
  url.searchParams.set("q", query);
  url.searchParams.set("limit", String(limit));
  url.searchParams.set("offset", String(offset));
  url.searchParams.set("rating", "g");
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GIPHY ${res.status}`);
  const json = await res.json();
  return (json.data ?? []).map((gif) => ({
    id: gif.id,
    title: (gif.title ?? "").trim(),
    sourceUrl: gif.url,
    preview: gif.images?.fixed_height_small?.url ?? gif.images?.fixed_height?.url,
    downloadUrl: gif.images?.fixed_height?.url,
    bytes: Number(gif.images?.fixed_height?.size ?? 0),
  }));
}
